apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/wazuh/wazuh-kubernetes
    targetRevision: v4.14.4
    path: wazuh

  destination:
    server: https://kubernetes.default.svc
    namespace: security

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
