grafana:
  adminPassword: admin123

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 7d

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

kubeEtcd:
  enabled: false
